name: ${project.parent.name}
version: ${project.version}
main: ${project.groupId}.${project.parent.name}.SpigotPlugin
api-version: 1.13
author: TibiNonEst

commands:
  reload:
    description: Server Status reload command
    usage: /serverstatus
