name: ServerStatus
version: ${project.version}
main: com.nexzcore.plugins.ServerStatus.SpigotPlugin
api-version: 1.13
author: TibiNonEst

commands:
  serverstatus:
    description: Server Status reload command
    usage: /serverstatus
    aliases:
      - ssr
      - ssreload
      - srvstatus
