# Port for the web server to run at
port: 80

# Name of the site
name: 'Minecraft Server'

# Server's max players
max_players: 20

# Background image for the site (optional)
# To remove set to ''
background_img: ''
